#!/usr/bin/env python3
"""列出 registry 中的 skill，并可重新生成 skills-index.md。

    uv run python tools/list_skills.py
    uv run python tools/list_skills.py --status stable
    uv run python tools/list_skills.py --write-index
    uv run python tools/list_skills.py --check-index
"""

from __future__ import annotations

import argparse
import json

from pathlib import Path
import sys

# 支持 `python tools/<name>.py` 直接运行（把仓库根加入 sys.path）。
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tools.console import ARROW, bold, configure_output, fail, ok, skip  # noqa: E402
from tools.registry import (
    REPO_ROOT,
    VALID_STATUSES,
    RegistryError,
    SkillEntry,
    load_registry,
)

INDEX_FILE = REPO_ROOT / "skills-index.md"
COLUMNS = ("NAME", "VERSION", "STATUS", "TARGETS", "PATH")


def filter_entries(entries: list[SkillEntry], status: str | None, include_archived: bool) -> list[SkillEntry]:
    selected = [entry for entry in entries if include_archived or not entry.archived]
    if status:
        selected = [entry for entry in selected if entry.status == status]
    return sorted(selected, key=lambda entry: entry.name)


def render_table(entries: list[SkillEntry]) -> str:
    rows = [
        (
            entry.name,
            entry.version,
            entry.status,
            ",".join(entry.targets) or "-",
            entry.path,
        )
        for entry in entries
    ]
    widths = [max(len(COLUMNS[i]), max((len(row[i]) for row in rows), default=0)) for i in range(len(COLUMNS))]
    lines = ["  ".join(COLUMNS[i].ljust(widths[i]) for i in range(len(COLUMNS))).rstrip()]
    lines.append("  ".join("-" * widths[i] for i in range(len(COLUMNS))))
    for row in rows:
        lines.append("  ".join(row[i].ljust(widths[i]) for i in range(len(COLUMNS))).rstrip())
    return "\n".join(lines)


def render_index(entries: list[SkillEntry]) -> str:
    active = [entry for entry in entries if not entry.archived]
    archived = [entry for entry in entries if entry.archived]

    lines = [
        "# Skills Index",
        "",
        "<!-- AUTO-GENERATED by tools/list_skills.py from registry/skills.yaml. Do not edit by hand. -->",
        "",
        "本文件是 [registry/skills.yaml](registry/skills.yaml) 的人类可读视图。",
        "重新生成：",
        "",
        "```bash",
        "uv run python tools/list_skills.py --write-index",
        "```",
        "",
    ]
    if active:
        lines += [
            "## Active Skills",
            "",
            "| Name | Version | Status | Targets | Description |",
            "| --- | --- | --- | --- | --- |",
        ]
        for entry in active:
            targets = ", ".join(f"`{t}`" for t in entry.targets) or "-"
            lines.append(f"| `{entry.name}` | {entry.version} | {entry.status} | {targets} | {entry.description} |")
        lines.append("")
        for entry in active:
            lines += [
                f"### {entry.name}",
                "",
                f"- 目录：`{entry.path}`",
                f"- 版本：`{entry.version}`　状态：`{entry.status}`",
                f"- 同步目标：{', '.join(entry.targets) or '-'}",
                f"- 说明：{entry.description}",
            ]
            if entry.notes:
                lines.append(f"- 备注：{entry.notes}")
            lines += [
                f"- 本地校验：`uv run python tools/validate_skills.py {entry.name}`",
                f"- 同步：`uv run python tools/sync_skills.py --target {entry.targets[0] if entry.targets else 'codex'} --skill {entry.name}`",
                "",
            ]
    else:
        lines += ["## Active Skills", "", "_暂无_", ""]

    if archived:
        lines += [
            "## Archived Skills",
            "",
            "归档 skill 默认不同步，只有显式 `--include-archived` 才会参与。",
            "",
            "| Name | Version | Status | Path |",
            "| --- | --- | --- | --- |",
        ]
        for entry in archived:
            lines.append(f"| `{entry.name}` | {entry.version} | {entry.status} | `{entry.path}` |")
        lines.append("")

    lines += [
        "## Workflow",
        "",
        f"{ARROW} 创建：`uv run python tools/new_skill.py <name>`",
        f"{ARROW} 校验：`uv run python tools/validate_skills.py`",
        f"{ARROW} 同步：`uv run python tools/sync_skills.py --target codex`",
        f"{ARROW} 自检：`uv run python tools/doctor.py`",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    configure_output()
    parser = argparse.ArgumentParser(description="List skills from the registry.")
    parser.add_argument("--status", choices=VALID_STATUSES, help="only show skills in this lifecycle status")
    parser.add_argument("--include-archived", action="store_true", help="include archived skills")
    parser.add_argument("--json", action="store_true", help="machine readable output")
    parser.add_argument("--write-index", action="store_true", help="regenerate skills-index.md from the registry")
    parser.add_argument("--check-index", action="store_true", help="exit 1 if skills-index.md is out of date")
    args = parser.parse_args(argv)

    try:
        entries = load_registry()
    except RegistryError as exc:
        print(fail(str(exc)))
        return 1

    selected = filter_entries(entries, args.status, args.include_archived)

    if args.check_index:
        content = render_index(entries)
        current = INDEX_FILE.read_text(encoding="utf-8") if INDEX_FILE.exists() else ""
        if current != content:
            print(fail("skills-index.md is out of date"))
            print("  fix: uv run python tools/list_skills.py --write-index")
            return 1
        print(ok("skills-index.md is up to date"))

    if args.write_index:
        INDEX_FILE.write_text(render_index(entries), encoding="utf-8", newline="\n")
        print(ok(f"wrote {INDEX_FILE.relative_to(REPO_ROOT).as_posix()}"))

    if args.json:
        print(json.dumps([entry.__dict__ for entry in selected], ensure_ascii=False, indent=2, default=list))
        return 0

    if not selected:
        print(skip("no skills match the filter"))
        return 0

    print(bold(render_table(selected)))
    print(f"\n{len(selected)} skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
